### PR TITLE
Fix No Camera bug, Port to Python3, Update to Sugargame v1.3

### PR DESCRIPTION
**Pull request by srevinsaju**
Tested Coverage - 98%

Known Issues:
The pygame uses hardcoded screen sizes. However, it would be working on all screens above `800x600` which was already an issue which existed on the master branch too. See #12 

Self-reviewed according to Review Guidelines. All tests passed

### CODE REVIEW

**Comment by srevinsaju** [comment]
Please review @quozl @chimosky @walterbender @Hrishi1999 @Aniket21Mathur

**Comment by chimosky** [comment]
Tested, made some changes and sent a PR to your repo.
Changes made
* Change except clause that starts camera to if statement as except clause seemed to have no explanation when there was one
* Make toolbar buttons insensitive when no camera is detected.

**Comment by quozl** [comment]
Tested with a camera.  The camera live image is on display, but the buttons are insensitive.  I did not diagnose.  Are you sure about not calling pygame.camera.init()?  Are you sure about hfilp spelling?

**Comment by chimosky** [comment]
> Tested with a camera. The camera live image is on display, but the buttons are insensitive. I did not diagnose. Are you sure about not calling pygame.camera.init()? Are you sure about hfilp spelling?

`pygame.camera.init()` was called as `camera.init()`, you're right it should be `hflip`. Can you diagnose when you have the time?, as the issue would most likely be from the value of`self._has_camera`.

**Comment by srevinsaju** [comment]
@chimosky I suspected that, hfilp is my mistake, I hadn't tested your changes. I will make those changes if something gone wrong.

**Comment by srevinsaju** [comment]
@chimosky fixed the typo on https://github.com/sugarlabs/panorama/pull/11/commits/6bf9c7a1aa4e6da063a76f7726a201fcf52445af. Seems like sugargame waits for the __init__ to get over and then starts the game. Maybe the has_camera has to be called within pygame file

**Comment by srevinsaju** [comment]
@chimosky @quozl I have added another commit here, it works now for me https://github.com/sugarlabs/panorama/pull/11/commits/942ad6183c36db12d7dbb76b2b3120c692b627ec

**Comment by chimosky** [comment]
> @chimosky fixed the typo on [6bf9c7a](https://github.com/sugarlabs/panorama/commit/6bf9c7a1aa4e6da063a76f7726a201fcf52445af). Seems like sugargame waits for the **init** to get over and then starts the game. Maybe the has_camera has to be called within pygame file

When self.game is initialized, `run` is called and when that happens `self._has_camera` will have it's value. `has_camera` doesn't need to be called within the pygame file - I assume you're talking about sugargame - as it's not used there.

**Comment by srevinsaju** [comment]
@chimosky did you compare the test between https://github.com/sugarlabs/panorama/pull/11/commits/f9a02f4bd2221833fb080c465fa5719d6a1bd629 and https://github.com/sugarlabs/panorama/pull/11/commits/942ad6183c36db12d7dbb76b2b3120c692b627ec

**Comment by quozl** [comment]
Tested as at https://github.com/sugarlabs/panorama/pull/11/commits/942ad6183c36db12d7dbb76b2b3120c692b627ec;

* on a native install to a laptop, the camera image is shown and controls work; though the stitching seems not to work very well, and there is a PyGIWarning for Gtk,
* on a virtual machine with no camera, the controls are still sensitive (should be insensitive), the canvas is not drawn on, and there is no message about no camera, but there was a traceback;

```log
Traceback (most recent call last):
  File "/usr/share/sugar/activities/Panorama.activity/pano.py", line 84, in run
    self.camera = camera.Camera(self.camlist[0], self.size, "RGB")
IndexError: list index out of range
```

**Comment by quozl** [comment]
Closes https://github.com/sugarlabs/panorama/pull/9.

**Comment by srevinsaju** [comment]
@quozl can you please check if you tested my branch on the VM? It seems like that error should not be created because it checks for !=0. If there is no camera, that block should  not have been executed in the first place. Tested on Sugar Debian Live 0.116. No errors

**Comment by quozl** [comment]
I agree, it must have been a mistake.  Tested 942ad6.  Still the PyGIWarning for Gtk.  Does say _Camera not found_, over on the right side of the display.  Does consume all CPU cycles.  Does mark buttons insensitive.

Could you fix the CPU issue?  Add a pygame.clock.

**Comment by srevinsaju** [comment]
@quozl the camera not found appearing too outside the screen is because the screen sizes were hardcoded to match the olpc infinity screen sizes. I will try to add the pygame.clock.

**Comment by quozl** [comment]
Thanks.  I can't find where the screen size is coded to any OLPC product.  Where is this in the code?

**Comment by srevinsaju** [comment]
I mean the standard olpc screen resolution,  I don't remember maybe 1280*768, I am not sure, previewing it on a higher resolution makes it look correct, we have to change the hardcoded screen resolution numbers to Gdk. Screen. width() /some value to make it look the same

**Comment by quozl** [comment]
OLPC XO was 1200x900 pixels.  I've looked again and can't find anything that says that in this repository.  My test VM is 1024x768 pixels.

**Comment by srevinsaju** [comment]
Yes @quozl the panorama activity is designed to look the best on 1200x900 resolution. If you try running it on a higher resolution, there will be still extra spaces below. I will try my best to use `Gdk.Screen.wifth()` and `height`

**Comment by srevinsaju** [comment]
@quozl fixed the CPU usage error on https://github.com/sugarlabs/panorama/pull/11/commits/57f80a70f2dac40f0e67930915edd66e95c57929 and fixed the warnings on https://github.com/sugarlabs/panorama/pull/11/commits/424141e3168207de6bd4d17953fdd25b4b09b222

**Comment by srevinsaju** [comment]
... -> PR :smile:

**Pull request merged**
