### PR TITLE
update sugargame to v1.3

### PR DESCRIPTION
**Pull request by ayushnawal**
Logs shows;
`Traceback (most recent call last):
  File "/home/ayush/activities/panorama/pano.py", line 84, in run
    self.camera = camera.Camera(self.camlist[0], self.size, "RGB")
IndexError: list index out of range
`
Reproduced the same error with master branch too, addressed it in #10

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  I'll wait for you to fix that problem before reviewing.  It looks important.

**Comment by ayushnawal** [comment]
Okay, I get it, no fix required for this error.

I didn't know that this activity would require any external camera as there was nothing mentioned as such in the readme, will update the readme ( insufficient for someone working with this activity for the first time).

Actually I didn't plug in an external camera so `camlist` was empty and so `self.camlist[0]` was giving index out of range error.

I will close the issue.

You can review now :grimacing:

**Comment by ayushnawal** [comment]
Also, please review this [PR](https://github.com/cristian99garcia/dasher-activity/pull/3).

I was unable to mention you there and the maintainers of this repo didn't respond, Thanks :grin:

**Comment by quozl** [comment]
Like with Pointillism, the activity must gracefully degrade and report if there is no camera rather than failing to start.  We have had a long term project at Sugar Labs to make sure that activities designed for the OLPC XO will work well on other computers.

**Comment by srevinsaju** [comment]
#11

**Pull request closed without merging**
